# Generated by Django 3.2.7 on 2021-09-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='choices',
        ),
    ]
